#!/bin/sh

LC_TIME="en_US"
export LC_TIME

die () {
   echo "*** mkconfig.sh: $*" 1>&2
   exit 1
}

[ -f makefile ] || die "can not find 'makefile'"

cat<<EOF
/*************************************************************/
/* Automatically generated by './mkconfig.sh': do note edit! */
/*************************************************************/
EOF

echo "#define LGL_OS \"`uname -srmn`\""
echo "#define LGL_COMPILED \"`date`\""
cat<<EOF
#define LGL_RELEASED "Thu Apr 12 18:16:02 CEST 2018"
#define LGL_VERSION "sc18"
#define LGL_ID "80c732d26c827cb5549def15cf647b4e6a33c070"
EOF
